export const mergeCode = [
  "if length(arr) <= 1: return arr",
  "mid = length(arr) / 2",
  "left = mergeSort(arr[0..mid])",
  "right = mergeSort(arr[mid..end])",
  "return merge(left, right)",
  "",
  "function merge(left, right):",
  "  result = []",
  "  while left and right:",
  "    if left[0] <= right[0]:",
  "      append left[0] to result",
  "      remove left[0]",
  "    else:",
  "      append right[0] to result",
  "      remove right[0]",
  "  append remaining left and right",
  "  return result",
];
